export default function TermsAndConditions() {
  return (
    <section className="terms-conditions-area ptb-100">
      <div className="container">
        <div className="section-title">
          <span className="sub-title">Terms & Conditions</span>
          <h2>Know Your Rights and Responsibilities</h2>
        </div>

        <div className="tnc-content">
          <div className="section-block">
            <p>
              This document is an electronic record in terms of the Information Technology Act, 2000 and rules thereunder,
              as applicable, and the amended provisions pertaining to electronic records in various statutes. This
              electronic record is generated by a computer system and does not require any physical or digital signatures.
            </p>
            <p>
              This document is published in accordance with Rule 3(1) of the Information Technology (Intermediaries
              Guidelines) Rules, 2011, which mandates publishing the rules and regulations, privacy policy, and Terms of
              Use for access or usage of domain name{' '}
              <a href="https://drkiranssmilegroup.com" target="_blank" rel="noopener noreferrer">
                https://drkiranssmilegroup.com
              </a>{' '}
              including its mobile site and application (hereinafter referred to as the ‘Platform’).
            </p>
            <p>
              The Platform is owned by <strong>SMILE DENTAL CLINIC, Hyderabad, India</strong>, a company incorporated under
              the Companies Act, 1956 with its registered office at Kukatpally, Medchal–Malkajgiri (hereinafter referred
              to as the ‘Platform Owner’, ‘we’, ‘us’, or ‘our’).
            </p>
          </div>

          <div className="section-block">
            <h3>1. Acceptance of Terms</h3>
            <p>
              Your use of the Platform and its services/tools are governed by the following Terms of Use. If you transact
              on the Platform, you are subject to these terms. By using the Platform, you enter a binding agreement with
              the Platform Owner. Please review the Terms regularly as they may change without prior notice.
            </p>
            <p>
              For the purpose of these Terms, ‘you’, ‘your’ or ‘user’ refers to any person accessing the Platform.
              ACCESSING, BROWSING, OR OTHERWISE USING THE PLATFORM INDICATES YOUR AGREEMENT TO ALL THE TERMS.
            </p>
          </div>

          <div className="section-block">
            <h3>2. User Responsibilities</h3>
            <ul>
              <li>
                You agree to provide accurate and complete information during registration and are responsible for all
                actions done through your account.
              </li>
              <li>
                You agree not to use the Platform or its Services for unlawful or illegal purposes, or in violation of
                applicable laws.
              </li>
              <li>
                You acknowledge unauthorized use may lead to legal action and/or termination of services.
              </li>
            </ul>
          </div>

          <div className="section-block">
            <h3>3. Warranty & Liability Disclaimer</h3>
            <ul>
              <li>
                We do not guarantee the accuracy, performance, or completeness of information provided on the Platform or
                through our Services.
              </li>
              <li>
                Your use of the Platform is entirely at your own risk, and you are responsible for evaluating the
                suitability of Services.
              </li>
              <li>
                Platform content is proprietary; unauthorized use may infringe copyright and result in legal action.
              </li>
            </ul>
          </div>

          <div className="section-block">
            <h3>4. Payments & Transactions</h3>
            <p>
              You agree to pay all charges associated with availing Services. Transactions on the Platform constitute a
              legally binding agreement with the Platform Owner.
            </p>
          </div>

          <div className="section-block">
            <h3>5. Third-party Links</h3>
            <p>
              The Platform may contain links to third-party websites. By accessing them, you are subject to their own
              terms, privacy policies, and other conditions. We are not responsible for the content or policies of these
              external websites.
            </p>
          </div>

          <div className="section-block">
            <h3>6. Indemnification</h3>
            <p>
              You shall indemnify and hold harmless the Platform Owner, affiliates, and staff from any claims, demands,
              penalties, or actions, including legal fees, arising from your breach of these Terms, Privacy Policy,
              applicable laws, or third-party rights.
            </p>
          </div>

          <div className="section-block">
            <h3>7. Force Majeure</h3>
            <p>
              We are not liable for any delay or failure in performance due to events beyond our control (force majeure),
              including natural disasters, government actions, or internet outages.
            </p>
          </div>

          <div className="section-block">
            <h3>8. Governing Law & Jurisdiction</h3>
            <p>
              These Terms are governed by the laws of India. All disputes shall be subject to the exclusive jurisdiction
              of the courts in Hyderabad, Telangana.
            </p>
          </div>

          <div className="section-block">
            <h3>9. Contact Information</h3>
            <p>
              For any questions or concerns regarding these Terms, please contact us using the details provided on our
              website.
            </p>
          </div>

          <p className="mt-4">
            <em>Last updated on: April 11, 2025</em>
          </p>
        </div>
      </div>
    </section>
  );
}
